name: Build Phase
on:
    push:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: subosito/flutter-action@v2
              with:
                channel: 'beta'
            
            - name: updating dependencies
              working-directory: ./app
              run: flutter pub get

            - name: testing app
              working-directory: ./app
              run: flutter test

            - name: building web version
              working-directory: ./app
              run: flutter build web
